Repository Todotodot/todotodot-server, pull requests merged in 2022-06, with the labels that each got.

#16 fix: Fix token access
  controllers/mainController.js
  middlewares/authorization.js
Labels: 버그수정

#17 fix: Fix group controller & expiration of secret key
  config/secretkey.js
  controllers/groupController.js
  controllers/mainController.js
  controllers/todoController.js
  routes/group.js
Labels: 버그수정

#19 feat: Implement connecting socket with client
  bin/www
  config/socket.js
Labels: 기능구현

#20 feat: Implement completeTodo endpoint
  controllers/todoController.js
  routes/group.js
  routes/index.js
  routes/user.js
Labels: 기능구현, 리팩토링

#21 chore: Change authorization logic to verify chrome-extension user
  middlewares/authorization.js
Labels: 자잘한변경

#22 chore: Add register process of extension user
  controllers/authController.js
  controllers/mainController.js
  loader/cors.js
  middlewares/authorization.js
Labels: 리팩토링, 자잘한변경

#25 refactor: Edit cors option to deploy
  loader/cors.js
Labels: 리팩토링

#26 refactor: Change esLint and prettier settings
  .eslintrc.js
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  config/firebase.js
  models/Group.js
  package-lock.json
  package.json
Labels: 리팩토링

#27 docs: Add readme
  README.md
Labels: 문서

#28 docs: Update restropect
  README.md
Labels: 문서
